name: Facebook Post Automation

on:
  schedule:
    # Run post generation every 2 hours
    - cron: '0 */2 * * *'
    # Run Facebook posting every 30-40 minutes (using a range)
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run (generate or post)'
        required: true
        default: 'generate'
        type: choice
        options:
          - generate
          - post

jobs:
  determine_task:
    runs-on: ubuntu-latest
    outputs:
      run_task: ${{ steps.set-task.outputs.task }}
    steps:
      - id: set-task
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "task=${{ github.event.inputs.task }}" >> $GITHUB_OUTPUT
          else
            # Determine task based on time
            minute=$(date +%M)
            if [[ $((minute % 30)) -eq 0 ]]; then
              # If minute is divisible by 30 (0 or 30), run both generate and post
              # But decide based on hour if this is a generation slot
              hour=$(date +%H)
              if [[ $((hour % 2)) -eq 0 ]]; then
                echo "task=generate" >> $GITHUB_OUTPUT
              else
                echo "task=post" >> $GITHUB_OUTPUT
              fi
            else
              # Otherwise just run post
              echo "task=post" >> $GITHUB_OUTPUT
            fi
          fi

  generate_posts:
    needs: determine_task
    if: needs.determine_task.outputs.run_task == 'generate'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai requests Pillow

      - name: Generate Facebook posts
        run: python .github/scripts/generate_facebook_posts.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/urls.txt data/processed_urls.txt data/pending_posts.csv
          git diff --staged --quiet || git commit -m "Generate new Facebook posts: $(date)"
          git push

  post_to_facebook:
    needs: determine_task
    if: needs.determine_task.outputs.run_task == 'post'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Random delay (30-40 minutes)
        run: |
          # Random delay between 0-10 minutes (0-600 seconds)
          # Only add delay if this is a scheduled run
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            DELAY=$((RANDOM % 600))
            echo "Adding random delay of $DELAY seconds"
            sleep $DELAY
          fi

      - name: Post to Facebook
        run: python .github/scripts/post_to_facebook.py
        env:
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/pending_posts.csv
          git diff --staged --quiet || git commit -m "Update Facebook post status: $(date)"
          git push